from rich_click.rich_click import (
    ALIGN_ERRORS_PANEL as ALIGN_ERRORS_PANEL,
    ERRORS_PANEL_TITLE as ERRORS_PANEL_TITLE,
    STYLE_ERRORS_PANEL_BORDER as STYLE_ERRORS_PANEL_BORDER,
    STYLE_HELPTEXT as STYLE_HELPTEXT,
    STYLE_HELPTEXT_FIRST_LINE as STYLE_HELPTEXT_FIRST_LINE,
    STYLE_USAGE as STYLE_USAGE,
    STYLE_USAGE_COMMAND as STYLE_USAGE_COMMAND,
)
from typing import Any

console: Any

def main(args: Any | None = ...): ...
